Published on January 19, 2025. By Prata, Marília (mpwolke)

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


#Visualizations libraries
import matplotlib.pyplot as plt
%matplotlib inline

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/resume-dataset/resume_data.csv

In [2]:
df = pd.read_csv('../input/resume-dataset/resume_data.csv')
df.head()

,address,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,...,online_links,issue_dates,expiry_dates,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score
0,NaN,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,['B.Tech'],['2019'],['N/A'],[None],['Electronics'],['Coca-COla'],...,NaN,NaN,NaN,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,NaN,Technical Support\nTroubleshooting\nCollaborat...,NaN,0.850000
1,NaN,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['N/A', 'N/A']","['N/A', 'N/A']","['Mathematics', 'Statistics']",['BIB Consultancy'],...,NaN,NaN,NaN,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),NaN,Machine Learning Leadership\nCross-Functional ...,NaN,0.750000
2,NaN,NaN,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['N/A'],['N/A'],['Electronics/Telecommunication'],['Axis Bank Limited'],...,NaN,NaN,NaN,"Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,NaN,"Trade Marketing Executive\nBrand Visibility, S...",Brand Promotion\nCampaign Management\nField Su...,0.416667
3,NaN,To obtain a position in a fast-paced business ...,"['accounts payables', 'accounts receivables', ...","['Martinez Adult Education, Business Training ...",['Computer Applications Specialist Certificate...,['2008'],[None],[None],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name...",...,NaN,NaN,NaN,Business Development Executive,Bachelor/Honors,1 to 3 years,Age 22 to 30 years,Apparel Sourcing\nQuality Garment Sourcing\nRe...,Fast typing skill\nIELTSInternet browsing & on...,0.760000
4,NaN,Professional accountant with an outstanding wo...,"['Analytical reasoning', 'Compliance testing k...",['Kent State University'],['Bachelor of Business Administration'],[None],['3.84'],[None],['Accounting'],"['Company Name', 'Company Name', 'Company Name...",...,[None],[None],"['February 15, 2021']",Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,NaN,iOS Lifecycle\nRequirement Analysis\nNative Fr...,iOS\niOS App Developer\niOS Application Develo...,0.650000

In [3]:
# Load English stopwords from nltk

import nltk

nltk.download("stopwords", quiet=True)

from nltk.corpus import stopwords

stopwords_english = stopwords.words("english")

#### We have Missing values,though they didn't affect my Top list.

In [4]:
df.isnull().sum()

address                                8760
career_objective                       4804
skills                                   56
educational_institution_name             84
degree_names                             84
passing_years                            84
educational_results                      84
result_types                             84
major_field_of_studies                   84
professional_company_names               84
company_urls                             84
start_dates                              84
end_dates                                84
related_skils_in_job                     84
positions                                84
locations                                84
responsibilities                          0
extra_curricular_activity_types        6118
extra_curricular_organization_names    6118
extra_curricular_organization_links    6118
role_positions                         6118
languages                              8844
proficiency_levels                     8844
certification_providers                7536
certification_skills                   7536
online_links                           7536
issue_dates                            7536
expiry_dates                           7536
﻿job_position_name                        0
educationaL_requirements                  0
experiencere_requirement               1364
age_requirement                        4087
responsibilities.1                        0
skills_required                        1701
matched_score                             0
dtype: int64

In [5]:
# Define preprocess_text function

def preprocess_text(text):
    
    '''
    This function preprocesses raw samples of text:
    - Converts to lowercase
    - Splits text on commas
    
    INPUT: 
    - text: "raw" text (string)
    
    OUTPUT:
    - processed_sample_tokens: list of tokens (list of strings)
    '''
    
    # Convert to lowercase
    text=str(text)
    clean_text = text.lower()
        
    # Replace common punctuation marks with whitespace
    pattern = r'[.;:\|\%\[\]\(\)\r\n\*]+'
    clean_text = re.sub(pattern,"", clean_text)
    
    # Replace single hyphens with whitespace
    clean_text = re.sub(r"\s-\s"," ", clean_text)       
 
    # Remove stop words and split on commas
    processed_sample_tokens = [tok for tok in clean_text.split(',') if tok not in stopwords_english]
    
    return processed_sample_tokens

In [6]:
from collections import Counter

import re

In [7]:
# 2nd alternative (using the apply method) 

df['clean_skils'] = df['skills'].apply(lambda x: preprocess_text(x))

# Show a sample
df.sample()

,address,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,...,issue_dates,expiry_dates,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score,clean_skils
4510,NaN,To secure a position that will allow me to exe...,"['Quality Assurance', 'Testing', 'Access', 'Qa...","['National Education Center', 'Kensington Trai...","['Minor', 'Testing Computer Software', 'BS']","['N/A', 'N/A', '1993']","['N/A', 'N/A', 'N/A']","['N/A', 'N/A', 'N/A']","['Management', 'N/A', 'Electrical Engineering']","['Company Name', 'Company Name', 'Company Name...",...,NaN,NaN,Site Engineer,Bachelor of Science (BSc) in Civil Engineering,1 to 2 years,Age 25 to 30 years,Supervision\nMonitoring\nConstruction\nEstimat...,AutoCAD\nCommunication and negotiation skills\...,0.65,"['quality assurance', 'testing', 'access', ..."

## Oh Boy, even skills was mispelled :D

In [8]:
df['clean_skils'].apply(lambda x: len(str(x).split(','))).sort_values(ascending=False)

5145    174
2461    174
5581    174
8410    174
4091    174
       ...
50        1
553       1
2775      1
6092      1
1073      1
Name: clean_skils, Length: 9544, dtype: int64

## Checking Skills required on entry 5145

It's Not very well splitted too. Not many skills um.... Why the slashes are still there? Damm it!

In [9]:
print(df['clean_skils'][5145])

["'technical support'", " 'telecom support'", " 'networking support'", " 'software/pc/lan troubleshooting'", " 'installing", ' configuring', ' troubleshooting windows', " linux and os x'", " 'installing", ' configuring', " troubleshooting soho networks'", " 'creating & updating documentation'", " 'software installation", ' configuring', " and troubleshooting'", " 'implementing", " configuring network and end user security'", " 'mobile device support'", " 'printer support'", " 'cli knowledge'", " 'voip", " video chat support'", " 'critical thinking with root cause analysis'", " 'encryption'", " 'file structures'", " 'network protocols'", " 'aaa security model'", " 'accounts and group policy'", " 'browser support'", " 'operating systems windows 7-10", ' ubuntu 1404', ' os x 108-1011', ' chromeos', ' ios9', " android'", " 'applications ms office 2010-2016 word", ' excel', ' powerpoint', ' outlook', ' google apps drive', ' docs', ' sheets', ' slides', ' keep', ' forms', ' sites', ' google drive sync client', ' internet explorer', ' firefox', ' chrome', ' safari', ' edge', ' openvpn', ' wireshark', ' sublime text', ' msra', ' microsoft rdp', ' openssh', ' puppet', " sccm 2012 ios-mdm'", " 'networking tcp/ip", ' dns', ' dhcp', ' lan/wan', ' vpn/remote connectivity openvpn', ' some basic cisco ios', ' microsoft virtual pc/hyper-v', ' teamviewer', ' terminal services', ' netgear', ' linksys', ' firewall', ' ports', " experience in routing & switching ospf / bgp / vlan / stp'", " 'hardware dell", ' hp', ' ibm/lenovo', ' apple', ' microsoft', ' desktop', ' laptops android smartphones tables', ' and wearables iphones and ipads printers', ' routers', ' switches', ' modems', ' wireless routers', ' video conferencing equipment tv', ' projectors', ' microphones', " speakers'", " 'security basic knowledge of ipsec / ssl-vpn / nat / gre", ' some experience with authentication protocols radius / tacacs', " strong desire to learn more'", " 'a+'", " 'active directory'", " 'antivirus'", " 'apple'", " 'bash'", " 'basic'", " 'bgp'", " 'cad'", " 'call center'", " 'ccna'", " 'cd-rom'", " 'cli'", " 'cisco ios'", " 'cisco'", " 'com'", " 'hardware'", " 'computer hardware'", " 'council'", " 'critical thinking'", " 'encryption'", " 'client'", " 'dell'", " 'dhcp'", " 'documentation'", " 'dns'", " 'edge'", " 'email'", " 'firewall'", " 'forms'", " 'help desk support'", " 'hp'", " 'ibm'", " 'insurance'", " 'internet explorer'", " 'lan'", " 'laptops'", " 'linux and os'", " 'linux'", " 'access'", " 'excel'", " 'mail'", " 'microsoft office'", " 'ms office'", " 'outlook'", " 'powerpoint'", " 'windows 7'", " 'microsoft windows'", " 'windows'", " 'word'", " 'modems'", " 'msi'", " 'networking i'", " 'network'", " 'networking'", " 'networks'", " 'operating systems'", " 'os'", " 'ospf'", " 'policies'", " 'printer'", " 'printers'", " 'protocols'", " 'python'", " 'routers'", " 'routing'", " 'scripting'", " 'software installation'", " 'solidworks'", " 'ssl'", " 'switches'", " 'system administration'", " 'tables'", " 'tcp/ip'", " 'tv'", " 'troubleshooting i'", " 'troubleshooting'", " 'video'", " 'video conferencing'", " 'vpn'", " 'voip'", " 'wan'"]

## Python Rules

At least, I was able to deploy my skills list made by Mr. KnowNothing (he knows plenty of DS)

In [10]:
#Mr. KnowNothing https://www.kaggle.com/code/tanulsingh077/twitter-sentiment-extaction-analysis-eda-and-model

top = Counter([item for sublist in df['clean_skils'] for item in sublist])
temp = pd.DataFrame(top.most_common(10))
#temp = temp.iloc[1:,:] #That removed Top ONE (salt)
temp.columns = ['Common_words','count']
temp.style.background_gradient(cmap='Purples')

## A vast Experience with Computers mentioned on My CV

"Denholm: I’m going **to put you in IT**, because you said on your CV, you have **a lot of experience with computers.**"

Jen: I did say that on my CV, yes. I have a lot of experience with **the whole computer thing**. You know, **emails, sending emails, receiving emails, deleting emails**, um… I could go on.

Denholm: Do.

Jen: **The web, using a mouse… mices, using mice, um… clicking, double clicking, um… the computer screen, of course… the keyboard**… the bit that goes on the floor down there.

Denholm: **The hard drive?**

Jen: Correct."

<iframe width="738" height="415" src="https://www.youtube.com/embed/e5NANrVnqLc" title="Jenn&#39;s Interview - The IT Crowd" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

#Acknowledgements:

Mr. KnowNothing https://www.kaggle.com/code/tanulsingh077/twitter-sentiment-extaction-analysis-eda-and-model